# prd env specific config
# Project Configuration
# project: "central-comp"  # Required Project identifier
# resource_index: "01"  # Resource index for tracking

# # Authentication Details
# service_principal_id: 
#   - "s789"  # 
# aad_group_object_id: 
#   - "a789" #

# # Metadata Tags
# tags:
#   Project Name: "Mad Framework Central Component"  # Descriptive project name
#   Type: "Mad Framework"  # Type of project
