name: Determine changed opcos
description: Checks which projects have changed since the last commit and outputs a list of changed projects
# outputs:
#   opco:
#     description: "The changed opco"
#     value: ${{ steps.changed_opcos.outputs.opcos }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: Determine changed files
      id: changed_files
      uses: tj-actions/changed-files@v45
      with:
        separator: ","
        files_ignore: .github/**
    
    - name: Determine changed opcos
      id: changed_opcos
      shell: bash
      run: |
       echo "${{ steps.changed_files.outputs.all_modified_files }}" | tr ',' '\n' | cut -d'/' -f1 | sort -u