name: Mad Central-Components for ALH
on:
  pull_request:
    branches:
      - main
    paths:
      - 'alh/central-comp/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write
env:
  OP_CO: alh
  target: central-comp
jobs:
  detect-components:
    name: Determine target components alh
    runs-on: ubuntu-latest
    outputs:
      environment_matrix: ${{ steps.target-comp.outputs.environment_matrix }}
    steps:
      - uses: actions/checkout@v4
 
      - name: Deploying target components
        id: target-comp
        uses: ./.github/actions/target
        with:
          opcopath: ${{ env.OP_CO }}
  deploy-component:
    name: Plan-cental-comp-${{ matrix.environment }}
    needs:  detect-components
    runs-on: ubuntu-latest
    env:
      OP_CO: alh
    strategy:
      matrix:
        environment: ${{ fromJson(needs.detect-components.outputs.environment_matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: merge config
        id: config
        uses: ./.github/actions/merge-config
        with:
          source: ./${{ env.OP_CO }}/${{ env.target }}/${{ matrix.environment }}-config.yaml
          target: ./${{ env.OP_CO }}/${{ env.target }}/project-config.yaml

      - name: Output config
        shell: bash
        id: tfconfig 
        run: |
          echo "Running job for ${{ env.OP_CO }}-${{ env.target }}-${{ matrix.environment }}"
          echo "deploy_config=${{ steps.config.outputs.config_path }}" >> $GITHUB_OUTPUT
          echo "backends_config=${{ env.OP_CO }}/backends/${{ matrix.environment }}.tfbackend" >> $GITHUB_OUTPUT
      
  # call-mad-flow:
  #   uses: vickydevopsorg/mad-core/.github/workflows/terraform.yml@main
  #   secrets: inherit
  #   needs: test
  #   with:
  #     environment: nonprd
  #     deployment_target: "central-comp"
  #     deploy_config: ${{ needs.test.outputs.deploy_config }}
  #     backends_config: "I am a backend"

  #     - name: print output
  #       shell: bash
  #       run: |
  #          echo "Printing all configs"
  #          echo "${{ steps.tfconfig.outputs.deploy_config }}"
  #          echo "${{ steps.tfconfig.outputs.backends_config }}"
  # check-mad-core:
  #   name: Test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: mad core
  #       id: mad-core
  #       uses: ./.github/actions/mad-core



      
  #     - uses: actions/checkout@v4
  #       name: mad-core checkout
  #       with:
  #        repository: vickydevopsorg/mad-core
  #        ref: main
  #        path: mad-core

  #     - uses: vickydevopsorg/mad-core/.github/actions/terraform
  #       with:
  #         environment: ${{ matrix.environment }}
  #         deployment_target: ${{ matrix.component }}
  #         backends_config: ${{ env.OP_CO }}/backends/${{ matrix.environment }}.tfbackend
  #         deploy_config: ${{ env.OP_CO }}/${{ matrix.component }}/config.yaml
      
      
