name: Target Mad Components for ALH
on:
  pull_request:
    branches:
      - main
    paths:
      - 'alh/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  detect-components:
    name: Determine target components alh
    runs-on: ubuntu-latest
    env:
      OP_CO: alh
    outputs:
      component_matrix: ${{ steps.target-comp.outputs.component_matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploying target components
        id: target-comp
        uses: ./.github/actions/target
        with:
          opcopath: ${{ env.OP_CO }}
  deploy-component:
    name: Plan ${{ matrix.environment }}-${{ matrix.component }}
    needs:  detect-components
    runs-on: ubuntu-latest
    env:
      OP_CO: alh
    strategy:
      matrix:
        environment: [nonprd, preprd, prd]
        component: ${{ fromJson(needs.detect-components.outputs.component_matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: merge config
        id: config
        uses: ./.github/actions/merge-config
        with:
          source: ./${{ env.OP_CO }}/${{ matrix.component }}/${{ matrix.environment }}-config.yaml
          target: ./${{ env.OP_CO }}/${{ matrix.component }}/project-config.yaml

      - name: Printing config yaml
        shell: bash
        run: |
          echo "Running job for ${{ env.OP_CO }}-${{ matrix.environment }}-${{ matrix.component }}"
          echo "config_path=${{ steps.config.outputs.config_path }}"
          cat ${{ steps.config.outputs.config_path }}
      
      - name: Backend config copy
        shell: bash
        run: |
          echo "Running backend for ${{ env.OP_CO }}-${{ matrix.environment }}-${{ matrix.component }}"
          echo "===== backend ==="
          cat ${{ env.OP_CO }}/backends/${{ matrix.environment }}-backend.yaml
      
      
      
