name: Target Mad Infra ALH changes
on:
  pull_request:
    branches:
      - main
    paths:
      - 'alh/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  detect_changes:
    name: Determine solution to deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Determine changed files
        id: changed_files
        uses: tj-actions/changed-files@v45
        with:
          separator: ","
          files_ignore: .github/**
      - name: List all changed files
        run: |
          echo "All changed files: ${{ steps.changed_files.outputs.all_modified_files }}"
          for file in ${{ steps.changed_files.outputs.all_modified_files }}; do
            echo "File changed: $file"
          done

        