name: Target Mad Infra ALH Central-comp changes
on:
  pull_request:
    branches:
      - main
    paths:
      - 'alh/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  detect_changes:
    name: Determine solution to deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Determine changed files
        id: changed_files
        uses: tj-actions/changed-files@v45
        with:
          separator: ","
          files_ignore: .github/**
      - name: List all changed files
        run: |
          CONFIG_PATHS="alh/central-comp/nonprd-config.yaml,gso/central-comp/project-config.yaml,alh/central-comp/project-config.yaml,gso/central-comp/nonprd-config.yaml,ebs/central-comp/nonprd-config.yaml"
          UNIQUE_OPCOS=$(echo "$CONFIG_PATHS" | tr ',' '\n' | cut -d'/' -f1 | sort -u | jq -R . | jq -s -c .)
          echo "Unique OPCOs: $UNIQUE_OPCOS"
          echo "::set-output name=opco_matrix::$UNIQUE_OPCOS"
          echo "All changed files: ${{ steps.changed_files.outputs.all_modified_files }}"
      
  deploy-opco:
    needs: detect_changes
    name: Deploying ${{ matrix.opco }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opco: ${{ needs.detect_changes.outputs.opco_matrix }}
    steps:
      - name: Plan ${{ matrix.opco }}
        shell: bash
        run: |
          echo "Running job for OPCO: ${{ matrix.opco }}"


        

        