name: Target Mad Components
on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  detect_changes:
    name: Determine solution to deploy
    runs-on: ubuntu-latest
    outputs:
      opco_matrix: ${{ steps.opco.outputs.opco_matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Opco change
        id: opco
        uses: ./.github/actions/opco

  deploy-opco:
    needs: detect_changes
    name: Deploying ${{ matrix.opco }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opco: ${{ fromJson(needs.detect_changes.outputs.opco_matrix) }}
    steps:
      - name: Printing
        shell: bash
        run: |
          echo "Running job for OPCO: ${{ matrix.opco }}"
      
      - name: Deploying target components
        id: target-comp
        uses: ./.github/actions/target-comp
        with:
          opcopath: ${{ matrix.opco }}
      
      # - name: printing
      #   run: |
      #     echo "changed files for opco ${{ matrix.opco }} are ${{ steps.target_comp.outputs.component_matrix }}"


        

        