name: Target Mad Infra ALH Central-comp changes
on:
  pull_request:
    branches:
      - main
    paths:
      - 'alh/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  detect_changes:
    name: Determine solution to deploy
    runs-on: ubuntu-latest
    outputs:
      opco_matrix: ${{ steps.opco.outputs.opco_matrix }}
    steps:
      - uses: actions/checkout@v4

      - name: Opco change
        id: opco
        uses: ./.github/actions/opco

  deploy-opco:
    needs: detect_changes
    name: Deploying ${{ matrix.opco }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opco: ${{ fromJson(needs.detect_changes.outputs.opco_matrix) }}
    steps:
      - name: Printing
        shell: bash
        run: |
          echo "Running job for OPCO: ${{ matrix.opco }}"


        

        