name: Target Mad Components for ALH
on:
  pull_request:
    branches:
      - main
    paths:
      - 'alh/**'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  # detect_changes:
  #   name: Determine solution to deploy
  #   runs-on: ubuntu-latest
  #   outputs:
  #     opco_matrix: ${{ steps.opco.outputs.opco_matrix }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Opco change
  #       id: opco
  #       uses: ./.github/actions/opco

  # deploy-opco:
  #   needs: detect_changes
  #   name: Deploying ${{ matrix.opco }}
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       opco: ${{ fromJson(needs.detect_changes.outputs.opco_matrix) }}
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Printing
  #       shell: bash
  #       run: |
  #         echo "Running job for OPCO: ${{ matrix.opco }}"
      
  #     # - name: Deploying target components
  #     #   id: target-comp
  #     #   uses: ./.github/actions/target
  #     #   with:
  #     #     opcopath: ${{ matrix.opco }}

  detect-components:
    name: Determine target components alh
    runs-on: ubuntu-latest
    env:
      OP_CO: alh
    outputs:
      component_matrix: ${{ steps.target-comp.outputs.component_matrix }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploying target components
        id: target-comp
        uses: ./.github/actions/target
        with:
          opcopath: ${{ env.OP_CO }}
  deploy-component:
    name: Plan ${{ matrix.environment }}-${{ matrix.component }}
    needs:  detect-components
    runs-on: ubuntu-latest
    env:
      OP_CO: alh
    strategy:
      matrix:
        environment: [nonprd, preprd, prd]
        component: ${{ fromJson(needs.detect-components.outputs.component_matrix) }}
    steps:
      - uses: actions/checkout@v4
      - name: merge config
        id: config
        uses: ./.github/actions/merge-config
        with:
          source: ./${{ env.OP_CO }}/${{ matrix.component }}/${{ matrix.environment }}-config.yaml
          target: ./${{ env.OP_CO }}/${{ matrix.component }}/project-config.yaml

      - name: Printing config
        shell: bash
        run: |
          echo "Running job for ${{ env.OP_CO }}-${{ matrix.environment }}-{{ matrix.component }}"
          echo "config_path=${{ steps.config.outputs.config_path }}"
          cat ${{ steps.config.outputs.config_path }}
      
      
