name: README Creation

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
    branches:
      - main
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Add environment specific details
      uses: ./.github/actions/readme
      with:
        usecase_folder: mad-demoteam101
